### ISSUE TITLE
The results are differenct from Grad_CAM paper and Web_Demo. 

### ISSUE THREAD

**Issue by gaobb** [ramprs/grad-cam#1]
This is a very interesting work! Thanks for your share. I found that there is a bit difference between your paper's result and web_demo's for cat visualization. The guided_cam result based on web_demo have some noises for "cat" (e.g., part of dog head).!
![web_demo result](https://cloud.githubusercontent.com/assets/9379079/19827353/ce69e7f8-9dd9-11e6-861a-22d80ba14e2d.png)
![paper reult](https://cloud.githubusercontent.com/assets/9379079/19827354/ce84749c-9dd9-11e6-824a-4f7d4ea48589.png)
I also reproduce the Grad_CAM experiments with MatConvNet. But my result is similar to your web_demo. I want to know that how to produce the paper's result.

![screenshot from 2016-10-29 12 53 38](https://cloud.githubusercontent.com/assets/9379079/19827407/8f933d16-9ddb-11e6-9d75-9f68f5e8815f.png)
![screenshot from 2016-10-29 12 54 18](https://cloud.githubusercontent.com/assets/9379079/19827408/9003ce28-9ddb-11e6-828e-01b04e81aa7e.png)

**Comment by abhshkdz** [comment]
Hi @gaobb, yeah, we're aware of it. The code and web demo are accurate. We'll update the paper figure, an rgb transpose bug crept through there :(

**Comment by abhshkdz** [comment]
The images in the repository readme are accurate though. Your matconvnet results look good!

**Comment by gaobb** [comment]
Thanks for your quick and effective reply.

**Comment by xiahuaxiebangmianjinpao** [comment]
I want to reproduce the Grad_CAM experiments with MatConvNet,can you send me your code  with MatConvNet?

**Comment by xiahuaxiebangmianjinpao** [comment]
@gaobb  I want to reproduce the Grad_CAM experiments with MatConvNet,can you send me your code with MatConvNet?Thank you very much!
