### ISSUE TITLE
Why do the results show linear or rectangular shape on heatmap?

### ISSUE THREAD

**Issue by mijung-kim** [ramprs/grad-cam#11]
Hello, 

I was wondering why the localized results show certain pattern like lines or rectangular shape. Anybody knows about the phenomenon? Thank you in advance!

**Comment by ramprs** [comment]
Hi Mijung,

       Are you referring to the rectangular patterns at the edges of the image? If so, this could be due to zero-padding the original image before feeding it to the network. Zero-padding introduces high gradients due to which some neurons might fire. And since Grad-CAM visualizations are a weighted sum of neuron activations, these effects become visible there as well.

**Comment by ramprs** [comment]
Hi Mijung,

       Are you referring to the rectangular patterns at the edges of the image? If so, this could be due to zero-padding the original image before feeding it to the network. Zero-padding introduces high gradients due to which some neurons might fire. And since Grad-CAM visualizations are a weighted sum of neuron activations, these effects become visible there as well.

**Comment by ramprs** [comment]
Hi Mijung,

       Are you referring to the rectangular patterns at the edges of the image? If so, this could be due to zero-padding the original image before feeding it to the network. Zero-padding introduces high gradients due to which some neurons might fire. And since Grad-CAM visualizations are a weighted sum of neuron activations, these effects become visible there as well.

**Comment by mijung-kim** [comment]
@ramprs, Yeah. I was wondering about it. Thank you so much!
