### ISSUE TITLE
Request to provide synset key

### ISSUE THREAD

**Issue by stmueller** [ramprs/grad-cam#16]
I have searched through the ILSVRC tables, and I cannot find any synsets where tigercat is 283 and boxer is 243:
Here is one example of the 1000 synsets:
http://image-net.org/challenges/LSVRC/2017/browse-synsets

Here, boxer is around line 90.
Can you provide a link to where I can retrieve the key mapping label-id, or upload a file with this key?

**Comment by abhshkdz** [comment]
https://github.com/Lasagne/Recipes/blob/master/examples/resnet50/imagenet_classes.txt
