### ISSUE TITLE
Visual question answering demo server does not respond

### ISSUE THREAD

**Issue by BAILOOL** [ramprs/grad-cam#3]
Testing the demo server for visual question answering results in the following:
```
Job published successfully
Publishing job to VQA Queue
Starting Visual Question Answering job...
Submitted demo image
```

**Comment by abhshkdz** [comment]
@BAILOOL Ah, thanks for reporting. We're looking into it.

**Comment by abhshkdz** [comment]
Fixed, the demo should work now (takes about 5-6 seconds per query).
