### ISSUE TITLE
How to compute the localization bounding box after get the saliency map?

### ISSUE THREAD

**Issue by lixiaosi33** [ramprs/grad-cam#6]
How to compute the localization bounding box after get the saliency map?
I want to have localization experiment, but trapped in this problem.
Many Thanks.

**Comment by ramprs** [comment]
I think the standard procedure is to binarize the heat map with threshold of 15% of the max intensity. This results in connected segments of pixels. Bounding box required for image localization can then be drawn around the single largest segment.

**Comment by zalkikar** [comment]
[This ](https://github.com/zalkikar/BBOX_GradCAM) might be helpful
