### ISSUE TITLE
why not just use Gradient-base to gain a saliency may

### ISSUE THREAD

**Issue by zhaoxinjie** [ramprs/grad-cam#9]

**Comment by zhaoxinjie** [comment]
Maybe I don't hnow clearly about this paper. but since we can get a saliency map just by gradient-base, why I get a CAM first, then use Guided-Backprop. Isn't just use gradient better? looking forward to your answer. thank you

**Comment by ramprs** [comment]
The visualizations obtained by taking the gradients wrt the input pixels for any target class is not class discriminative. See figure 2 of the grad cam paper for an example. In our work we compute the gradients with respect to the convolution layer and do a weighted combination to get Grad-CAM (coarse heatmap). We can combine with this with other pixel level visualizations that are high resolution (but not class discriminative such as Guided Backprop) to get a high resolution class discriminative visualization-Guided Grad-CAM. Please let me know if it clears your doubt.

By CAM, I think you mean Grad-CAM. The Grad in Grad-CAM refers to the gradient they we compute wrt the last convolution layer

**Comment by zhaoxinjie** [comment]
thank for your answer，i'm clear now.
